### ISSUE TITLE
Errors due to path problems

### ISSUE THREAD

**Issue by ShantanuDash** [benjaminbolling/RSW#2]
Having spaces in the folder names seems to cause problems

```
D:\joss review\RSW>python RSW.py
python: can't open file 'D:\joss': [Errno 2] No such file or directory
```

Replacing space with hyphen removes the problem.

```
D:\joss-review\RSW>python RSW.py

D:\joss-review\RSW>
```

Possible solutions:
- https://stackoverflow.com/questions/50011733/python-error-filenotfounderror-errno-2-no-such-file-or-directory/50011910
- https://stackoverflow.com/questions/12201928/python-open-gives-filenotfounderror-ioerror-errno-2-no-such-file-or-directory

openjournals/joss-reviews#3431

**Comment by benjaminbolling** [comment]
Thank you! However, I believe this is an issue from your local test environment, as joss review is not a folder defined by the repo.

**Comment by ShantanuDash** [comment]
Joss review folder has the repo inside it.
So the problem arises due to the reasons given in the Stackoverflow I've linked above.

If the changes seem too cumbersome then you could add a suggestion for users _to not have space separated directories_ .

**Comment by benjaminbolling** [comment]
My apologise, I see what you mean. I will fix this during the evening.

**Comment by benjaminbolling** [comment]
Sorry for the delay, got caught up in other work. Seems to be working now, please verify it this is the case @ShantanuDash.

**Comment by ShantanuDash** [comment]
> Sorry for the delay, got caught up in other work. Seems to be working now, please verify it this is the case @ShantanuDash.

No problems.

I works fine now!
